version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: shopzone-postgres
    environment:
      POSTGRES_DB: shopzone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - shopzone-pgdata:/var/lib/postgresql/data

volumes:
  shopzone-pgdata: